### ISSUE TITLE
'Create diploid' button obscured by genotype actions

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1929]
(Caused by #1871)

If you have no diploid genotypes in a curation session, and you add a new single locus genotype, the 'Create diploid ...' button is covered by a popup (that automatically shows) containing the genotype row links (for edit, delete, etc):

![diploid_button_obscured](https://user-images.githubusercontent.com/37659591/59263622-521a7180-8c39-11e9-86a9-1904e7a98fb3.PNG)

This stops being a problem after you create at least one diploid genotype, because the button is then pushed down below the next table:

![diploid_button_visible](https://user-images.githubusercontent.com/37659591/59263668-6c544f80-8c39-11e9-878f-b699fe1ba27a.PNG)

I think it would be better if the buttons rendered below each other to start with:

![diploid_button_below](https://user-images.githubusercontent.com/37659591/59263917-ee447880-8c39-11e9-8f9f-cdaaf69206c7.PNG)

The only other option that I can see is to _not_ show the genotype links automatically, but I think this just trades one usability problem for another.

**Comment by jseager7** [comment]
@kimrutherford I've also just noticed (in the images above) that the button text seems to change from 'Create diploid...' to 'Create diploid locus...' after you've added one diploid genotype. Is this intentional, or should the text stay as 'Create diploid...'?

**Comment by kimrutherford** [comment]
> the 'Create diploid ...' button is covered by a popup

Perhaps the easiest fix is to have a minimum width on the tables.  Does that sounds OK? 

> I've also just noticed (in the images above) that the button text seems to change from 'Create diploid...'
> to 'Create diploid locus...' after you've added one diploid genotype. Is this intentional, or should the
> text stay as 'Create diploid...'?

Thanks for that.  The text is in two places but I only changed one.  I've pushed a fix.

**Comment by jseager7** [comment]
> Perhaps the easiest fix is to have a minimum width on the tables. Does that sounds OK?

I guess that could work, providing it doesn't interfere with the flexbox layout, and if it doesn't risk pushing the genotype tables onto a new row on narrower screens. I haven't tested that yet.

**Comment by kimrutherford** [comment]
> Perhaps the easiest fix is to have a minimum width on the tables.

I tried that and it didn't look great.

> I think it would be better if the buttons rendered below each other to start with:

I'd be happy with that but let's come back to this after deciding on: #1945

**Comment by ValWood** [comment]
This issue is only present of. the allele names are short.
A simple solution would be to  'pad' the genotype table "allele field" to make the table  overhang the buttons?
<img width="741" alt="Screenshot 2022-03-28 at 20 48 42" src="https://user-images.githubusercontent.com/7359272/160475586-4352cf9d-6755-4d60-9ff1-a9ef3b941a6e.png">

**Comment by jseager7** [comment]
@ValWood It can still happen on the shortest allele names, but we haven't had anybody at PHI-base complain about it.

I think the diploid table display might have changed in the meantime, which means that the button can still be obscured after creating one diploid genotype:

<img width="846" height="333" alt="Image" src="https://github.com/user-attachments/assets/6a454752-e995-4412-89e4-adf6396ef4a5" />

One related problem is that the tick-box to select a genotype also shows the pop-up menu, because the tick-box is within the mouse-hover area that triggers showing the pop-up. So basically, selecting a genotype obscures the button.

The worst possible sequence for the user is as follows:

1. The user creates a short haploid genotype
2. The 'Create diploid locus' button is obscured by the pop-up menu
3. The user closes the pop-up menu
4. The user then realises that a genotype has to be selected to enable the 'Create diploid locus' button
5. The user enables the tick-box to select the genotype
6. The pop-up menu is shown again, obscuring the button
7. The user closes the pop-up menu again

But if short allele names are not common in PHI-base (and I suspect they're not common), then this is a non-issue for us.
