### ISSUE TITLE
Make tooltips more responsive on mouse-over

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2397]
This has always been a bit of a bug-bear,  but  this is often so slow that it does not appear when you hover over.

For instance here:
<img width="408" alt="Screenshot 2021-01-26 at 15 59 15" src="https://user-images.githubusercontent.com/7359272/105869734-7635ec80-5fef-11eb-8f88-f5b508548172.png">

New users really need to know why they can't make phenotype annotations at this point. I expected a pop-up but did not see one.  I eventually saw it appear a while later.

Is there a different plug in  that would do this more quickly (or maybe  it's a precision issue? does it only work when you are precisely over the text, and not the text background?). 

Also, I wondered why  "pathogen host interaction phenotype" was not greyed out at this point too?

**Comment by ValWood** [comment]
I see now that "pathogen host interaction phenotype"  has a clickable pop-up. I think we should be consistent here.

Also 
Metagenotype pop-up says
"Add at least one host organism and at least one pathogen genotype to make a metagenotype.

Maybe it would be useful to say
Metagenotypes are used to curate "pathogen-host interaction phenotypes". Add at least one host organism and at least one pathogen genotype to make a metagenotype.

This would make it easier for  people to connect  the genotype type to the phenotype type in their minds.

**Comment by ValWood** [comment]
I was in advance mode for all the above comments.
Is advanced mode available to users?

**Comment by kimrutherford** [comment]
> New users really need to know why they can't make phenotype annotations at this point. I expected a pop-up but did not see one. I eventually saw it appear a while later.

We're currently using the build in browser functionality for those pop-ups.  There is no control over how long the browser waits.  It's quite quick in Firefox.  We can change to use a library to make more fancy pop-up where we can control the wait time.

> Is there a different plug in that would do this more quickly

We'll use the same library we use in other places.  We don't use it very often.  We should be more consistent.

> (or maybe it's a precision issue? does it only work when you are precisely over the text, and not the text background?).

That will currently depend on the browser and possible the OS.  We'll have more control when we switch to using the library.

> Also, I wondered why "pathogen host interaction phenotype" was not greyed out at this point too?

Just an oversight I think.

> I see now that "pathogen host interaction phenotype" has a clickable pop-up. I think we should be consistent here.

Yep, definitely.  I think that pop-up is for meant for genotype-genotype interactions which is why the text is a bit odd.  As you say it would be better to be consistent so I think we should have a mouse-over in this case, not a pop-up.  We can use your suggested text in a mouse-over instead of a pop-up. 

> Is advanced mode available to users?

Yep, it's available to all users, but it's off by default for new users.


@jseager7: I'm think of using uib-tooltip for these mouse-overs.

**Comment by kimrutherford** [comment]
> Also, I wondered why "pathogen host interaction phenotype" was not greyed out at this point too?

I've fixed that problem.

@jseager7 could you re-deploy PHI-Canto when you get a chance?

**Comment by kimrutherford** [comment]
>  We can change to use a library to make more fancy pop-up where we can control the wait time.

I've changed from the build-in browser tool-tips to the code we use in a few other places.  It pops up instantly for me now.  I haven't made any changes to the text yet.

**Comment by ValWood** [comment]
It pops up faster (possibly?)  but I still seem to need to be very precise with my mouse-over in order for the pop-up to appear (using PomBase Canto)
Note that PomBase Canto does not seem to have pop-up for "genotype management" or "quick-links". I tested on the gene page-specific links.

**Comment by kimrutherford** [comment]
> It pops up faster (possibly?) but I still seem to need to be very precise with my mouse-over in order for the pop-up to appear (using PomBase Canto)

Sorry, I should have said, because your screenshot with from PHI-Canto, I've only changed the main Canto code not the old code used by pombe Canto.

> Note that PomBase Canto does not seem to have pop-up for "genotype management"

There isn't a pop-up for that yet.  I can add one if you let me know what text you'd like.

The quick links in pombe Canto are never greyed out so you won't see any pop-ups there.

**Comment by ValWood** [comment]
OK, will test when in PHI-Canto

**Comment by jseager7** [comment]
@kimrutherford Thanks for the help. I'll deploy this on the server shortly.

**Comment by jseager7** [comment]
@ValWood I've deployed this change on both the main and demo server now. If you want to test it immediately, I've created a session on the demo server with no alleles or host species added: [PMID:999999](https://demo-canto.phi-base.org/curs/480c0207511a9e56)

**Comment by ValWood** [comment]
Much better, thanks for that!

**Comment by kimrutherford** [comment]
> >   Note that PomBase Canto does not seem to have pop-up for "genotype management"
>
> There isn't a pop-up for that yet. I can add one if you let me know what text you'd like.

If you let me know what text you'd like, I'll add it and then close the issue.

**Comment by ValWood** [comment]
Add, view and edit genotypes. To make multi-locus phenotype annotations genotypes must be combined here first.

In the single gene workflow we could also add
Single allele Phenotype 
pop-up 
Add single gene allele and phenotype annotations.  To make multi-locus phenotype annotations genotypes must be created and combined in "Genotype management" first.

I think this would be useful as we still get questions about this part of the workflow.

@mah could you edit?

**Comment by mah11** [comment]
> @mah could you edit?

First, two questions:

- Is the text intended for PomBase or PHI-canto? PomBase Canto already has help text for "Genotype management" on the summary page and for each of the curation types on gene pages. It appears when you mouse over the "?" (at least it does for me).

- Whichever instance these are for, could you make it clearer which existing help text should be changed to what new text (and which bits are just the ticket comment, not meant to appear in Canto itself)?

thanks :)

**Comment by ValWood** [comment]
Sorry, not clear, these texts are for PomBase.
Right, I thought the question marks only linked to the docs, I didn't realise they also had a pop-up.

It might be useful if  the first point  for single gene phenotypes was clearly more clearly "you need to go to genotypes first to make multi-locus phenotype annotations" This is  still one of the most common mistakes. Either people still as how to do multi-locus, or quite often they will stick the other gene in conditions field, or a comment. An up front reminder would. be useful.

I bolded the points I was trying to make above. 

Maybe we can we extend 
"one or more mutations or an expression change in one copy of a gene at one locus"

to
Use for one or more mutations or an expression change in one copy of a gene at one locus. To create multi-locus phenotype annotations genotypes must first be created and combined in "Genotype management".

would that work?

Also, would there be any objection to making the mouse over appear on  mouse over the text in addition to the "?"

**Comment by jseager7** [comment]
> Also, would there be any objection to making the mouse over appear on mouse over the text in addition to the "?"

If the tooltips appear immediately then it could get a bit distracting for curators if they glide their mouse over the list when choosing an option. Tooltips are typically more common for parts of the user interface that are inherently ambiguous, like icons, not so much for text links that are already somewhat self-explanatory.

If we do decide to have tooltips on the links then I don't think we should have the same text on the help icons as well. It just seems redundant.

I think I'd be in favour of personalising the text in the tooltips on the help icons (offering more guidance about the relevant annotation type), because currently the text is all very generic: 'Click for help on [annotation type] (Click to visit documentation)'

**Comment by ValWood** [comment]
OK tool tips should be restricted to the icons. I agree they would be distracting.  Probably the more responsive pop-ups will improve this a lot anyway. We don't see this yet in pombe-Canto

**Comment by mah11** [comment]
Well, I've just realized that part of the issue here is that the "?"s don't all behave the same way. The ones in headers just spawn little "sticky" popups with a slightly different look than the tooltips (see me using my new vocabulary).

Furthermore, "Genotype management" has a relevant "?" with a popup in the "Annotate genotypes" header on the summary page, but doesn't have the kind of "?" that links to the relevant [documentation](https://curation.pombase.org/pombe/docs/fypo_annotation#multi-allele-phenotypes) anywhere.

So ... in light of the most recent comments from Val and James, I gather we could do with:

- updated text for all of the tooltips in the curation type list on the gene-specific pages

- updated text for the "Annotate genotypes" header "?" popup

- new tooltip text for "Genotype management", to include a documentation link.

If that sounds right I'll work on the text.

**Comment by mah11** [comment]
on this point

>>  Also, would there be any objection to making the mouse over appear on mouse over the text in addition to the "?"
> 
> If the tooltips appear immediately then it could get a bit distracting for curators if they glide their mouse over the list when choosing an option.

I don't use the gene-specific pages anywhere near often enough to have a strong preference. But more generally, I do find over-eager tooltips annoying (e.g. on the GitHub ticket lists ... those are positively maddening, and there's more than one kind!!!) because they tend obscure link text that I was trying to read.

**Comment by ValWood** [comment]
> If that sounds right I'll work on the text.

Please, that would be brill.

>But more generally, I do find over-eager tooltips annoying 

OK agreed, it would be annoying to see them all the time.

**Comment by jseager7** [comment]
> Well, I've just realized that part of the issue here is that the "?"s don't all behave the same way. The ones in headers just spawn little "sticky" popups with a slightly different look than the tooltips (see me using my new vocabulary).

The ones that spawn pop-ups are using some older code, and there's really no reason for the inconsistency, especially on the gene page. They should probably all be migrated to the tooltip system, so I'll open an issue for that.

**Comment by mah11** [comment]
OK, here's the first chunk of suggestions: On the summary page, change "Annotate genotypes" popup text (I think this is independent of whether it changes to tooltip style).

PomBase version:
Add single- or multi-locus genotypes, for haploids or diploids, to use in annotating phenotypes. Genotypes include alleles, expression levels, and optional background details. You can add genotypes individually as you go through the paper, or all at once before you start adding phenotype annotations.

PHI-Canto version:
Add single- or multi-locus genotypes for hosts or pathogens, and combine host and pathogen genotypes into metagenotypes, to use in annotating phenotypes. Genotypes include alleles, expression levels, and optional background details. You can add genotypes individually as you go through the paper, or all at once before you start adding phenotype annotations.

**Comment by mah11** [comment]
And here are tooltip suggestions for the curation types on gene-specific pages:

|type | PomBase tooltip text |
|---------------|----------|
| GO molecular function | Annotate a gene product's molecular activity. Click "?" to visit documentation. |
| GO biological process | Annotate a gene product's role in a process. Click "?" to visit documentation. |
| GO cellular component | Annotate the location in a cell where a gene product acts. Click "?" to visit documentation. |
| Single allele Phenotype | Annotate phenotypes for single mutants (i.e. mutation(s) or expression change in one copy of a gene at one locus). Use "Genotype management" for multi-locus (e.g. double mutant) genotypes and their phenotypes. Click "?" to visit documentation. | 
| Protein modification | Annotate the type, position, timing, etc. of covalent protein modifications. Click "?" to visit documentation. |
| Wild-type RNA level | Annotate qualitative descriptions for the normal level and timing of RNA expression from a gene. Click "?" to visit documentation. |
| Wild-type Protein level | Annotate qualitative descriptions for the normal level and timing of protein expression from a gene. Click "?" to visit documentation. |
| Genetic interaction | Annotate interaction type and interacting genes. Click "?" to visit documentation.|
| Physical interaction | Annotate interacting gene products and supporting evidence. Click "?" to visit documentation. |


Notes:

-  Val's suggestion for PHI-Canto gene expression tooltips included "location" but tissue types aren't yet available as extensions (requested in #2400). When they are in, change "normal level and timing" to "normal level, timing, and location" for both RNA and protein level.
- I have tried to keep the tooltip messages brief, because browsers don't always display them very readably, and because there's no point trying to cram lots of detail in; that's what the main documentation is for (so I also retained the pointer to click for more).
- Later, when #2301 is done, change the Genetic interaction tooltip to "Annotate interaction type, interacting genotypes and phenotypes. Click "?" to visit documentation.".

**Comment by ValWood** [comment]
Looks good.

**Comment by jseager7** [comment]
These changes are ready to be enabled now. Some notes:

* These changes only apply to the help icons next to the curation type links on the gene page, not to the Quick Links section that shows on the Summary page in Advanced mode. I'm not sure if this issue was initially meant to be about the Quick Links section, but the Quick Links don't have help icons; we might be able to add help icons there as well, if that's what was actually being requested.

* I've left out the text for 'Click "?" to visit documentation' because the similar text '(Click to visit documentation)' is included by default. I could amend the default text, although 'Click "?"' might be redundant if the tooltip is already applied to the help icon.

* The tooltip text will be applied to every version of Canto, since the text is specified by the default configuration file (canto.yaml). Any users of Canto are free to override this text using their specific configuration file (canto_deploy.yaml). If you think that any of the proposed text is not generally applicable to all versions of Canto, please let me know and we can replace it with something more generic.

* The Single Allele Phenotype tooltip already had customised text by default; the new text is about twice the length of the original, although I think the potential readability issues are more to do with the awkward text wrapping caused by the narrow width of the tooltip, and the use of centred text, rather than the length of the text. Either of those things could be adjusted.

![image](https://user-images.githubusercontent.com/37659591/109138090-e8663200-7751-11eb-8997-a1448e65921d.png)

**Comment by ValWood** [comment]
OK should we go ahead and implement these changes?

**Comment by jseager7** [comment]
Note that the changes are already enabled for PHI-Canto. I'm not sure about PomBase version of Canto, since I think that's being held behind the latest release of the code.

**Comment by ValWood** [comment]
OK can close. If there are any issues we can open new tickets once we are in synch...
