### ISSUE TITLE
appropriate existing phenotype is not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2636]
For creating a phenotypic supression/rescue here,

<img width="925" alt="Screenshot 2022-09-20 at 12 00 27" src="https://user-images.githubusercontent.com/7359272/191241448-b76d3e78-0d0d-403c-89e9-d030f9bc1161.png">

This existing skb1Δ phenotype would be appropriate

<img width="922" alt="Screenshot 2022-09-20 at 12 00 54" src="https://user-images.githubusercontent.com/7359272/191241536-13c1dfe5-b699-42fa-a35e-528ad3387bd3.png">

but is not displayed as a selectable option

**Comment by ValWood** [comment]
Also here, when I tried to add an annotation manually to check further, the available phenotypes are restricted to population phenotypes when. they should be none population phenotypes

**Comment by manulera** [comment]
Maybe related to #2634

**Comment by kimrutherford** [comment]
> Also here, when I tried to add an annotation manually to check further, the available phenotypes are restricted to population phenotypes when. they should be none population phenotypes

Could you explain that more?  I don't understand.

**Comment by ValWood** [comment]
The wrong phenotype  options were available in the autocomplete when I tried to make new phenotype annotations.

**Comment by kimrutherford** [comment]
Thanks.  Which session was that?

**Comment by kimrutherford** [comment]
> The wrong phenotype options were available in the autocomplete when I tried to make new phenotype annotations.

Thanks, that's fixed now.

I still need to work on why the existing skb1Δ phenotype isn't offered.

**Comment by ValWood** [comment]
I was testing in test/curs/4c718237e0521f89

**Comment by kimrutherford** [comment]
I think the code is OK but the database needs fixing:
   - #2642

**Comment by kimrutherford** [comment]
> This existing skb1Δ phenotype would be appropriate
>
> but is not displayed as a selectable option

I've applied the fix from #2642 to the test Canto instance so this appears to be fixed.  But I wasn't sure exactly which annotations and interaction types you were using when you spotted the problem.  Could you have a test when you get a chance?

**Comment by ValWood** [comment]
I don't think it is quite right still.

Using the same session when I select phenotypic enhancement and then check 

Select the skb1delta phenotype(s) other than growth defect or lethality enhanced by cdc2-3w(aaC67Y)[Not assayed]

I still get the growth/viability phenotypes in addition to the expected non population phenotype
"viable elongated vegetative cell"

**Comment by ValWood** [comment]
Sorry, I forgot the screen shot:
<img width="1150" alt="Screenshot 2022-09-28 at 11 53 36" src="https://user-images.githubusercontent.com/7359272/192761966-8504f4d9-fde8-44f3-b00d-999e772f7563.png">

**Comment by ValWood** [comment]
I think it is OK then!

**Comment by kimrutherford** [comment]
Great.  Let's close this one then.
